<a href="https://colab.research.google.com/github/Layab123/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 0_D Array

In [ ]:
import numpy as np
arr=np.array(25)
print(arr)
print("type of array:", type(arr))


25
type of array: <class 'numpy.ndarray'>


## 1_D Array

In [ ]:
import numpy as np

arr_1d=np.array([1,4,10])
print(arr_1d)

[ 1  4 10]


## 2_D Array

In [ ]:
import numpy as np
arr_2d=np.array([[1,5,3,9],[8,7,5,3]])
print("tow Dimesional Array:")
print(arr_2d)
print()
print(type(arr_2d))
print()
print("type of dimensional:",arr_2d.ndim)

tow Dimesional Array:
[[1 5 3 9]
 [8 7 5 3]]

<class 'numpy.ndarray'>

type of dimensional: 2


## 3_D Array

In [ ]:
import numpy as np
arr_3d=np.array([[[1,4,23,54],[23,45,98,12]]])
print("value of Numpy:",arr_3d)
print()
print(type(arr_3d))
print()
print("number of dimensional array",arr_3d.ndim)

value of Numpy: [[[ 1  4 23 54]
  [23 45 98 12]]]

<class 'numpy.ndarray'>

number of dimensional array 3


## Higher dimensional Array

In [ ]:
import numpy as np
arr=np.array([123,45,6], ndmin=4)
print(arr)

[[[[123  45   6]]]]


## Higher dimensional array with 2_D array

In [ ]:
import numpy as np
arr=np.array([[2,3,4]],ndmin=32)
print(arr)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[2 3 4]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


##higher_D Array with 0_D Array

In [ ]:
import numpy as np
arr=np.array(45,ndmin=2)
print(arr)

[[45]]


##

In [ ]:
import numpy as np
zero_d=np.array(24)
one_d=np.array([3,5,7,8])
tow_d=np.array([[12,4,6],[2,4,3]])
three_d=np.array([[[3,4,6,7,],[5,9,7,2]]])
higher_d=np.array([1,3,5],ndmin=4)
print("class or type of ndarray:")
print(type(zero_d))
print(type(one_d))
print(type(tow_d))
print(type(three_d))
print(type(higher_d))
print()
print("Different type of Dimensional Array:")
print("type of dimensional:",zero_d.ndim)
print("type of dimensional:",one_d.ndim)
print("type of dimensional",tow_d.ndim)
print("type of dimensional",three_d.ndim)

print("number of dimensional array:",higher_d.ndim)
print()
print("print the Array:")
print()
print("0_D Array:",zero_d)
print()
print("1_D Array:",one_d)
print()
print("2-D Aray:",tow_d)
print()
print("3_D Array:",three_d)

print()
print("n_D Array:",higher_d)

class or type of ndarray:
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

Different type of Dimensional Array:
type of dimensional: 0
type of dimensional: 1
type of dimensional 2
type of dimensional 3
number of dimensional array: 4

print the Array:

0_D Array: 24

1_D Array: [3 5 7 8]

2-D Aray: [[12  4  6]
 [ 2  4  3]]

3_D Array: [[[3 4 6 7]
  [5 9 7 2]]]

n_D Array: [[[[1 3 5]]]]
